# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorepo < Formula
  desc "A cli to manage Go monorepos"
  homepage "https://github.com/gorepo-cli/gorepo"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gorepo-cli/gorepo/releases/download/v1.3.0/gorepo_1.3.0_darwin_amd64.tar.gz"
      sha256 "d4708c2bf5546b649854b4498a467e3fef5ca5d505d2b86ce45772e7f11be334"

      def install
        bin.install "gorepo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gorepo-cli/gorepo/releases/download/v1.3.0/gorepo_1.3.0_darwin_arm64.tar.gz"
      sha256 "5b902e6f789f7f283a7a02c6d44f7db963e893bfa17da6ff2889755a85de3094"

      def install
        bin.install "gorepo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gorepo-cli/gorepo/releases/download/v1.3.0/gorepo_1.3.0_linux_amd64.tar.gz"
        sha256 "3cdd5fece7f8390db940dd294b258b4aae3b0844c24a6200bb5f4cbfe31a3829"

        def install
          bin.install "gorepo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gorepo-cli/gorepo/releases/download/v1.3.0/gorepo_1.3.0_linux_arm64.tar.gz"
        sha256 "90ce396e1c1d2652bd462797cd4d433128e9233968771de47f8557137815a23f"

        def install
          bin.install "gorepo"
        end
      end
    end
  end
end
