# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorepo < Formula
  desc "A cli to manage Go monorepos"
  homepage "https://github.com/gorepo-cli/gorepo"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gorepo-cli/gorepo/releases/download/v1.2.1/gorepo_1.2.1_darwin_amd64.tar.gz"
      sha256 "7c97f1e7df35d9afb6d60d51937440f6992d921782a5b4a7969251931da0473c"

      def install
        bin.install "gorepo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gorepo-cli/gorepo/releases/download/v1.2.1/gorepo_1.2.1_darwin_arm64.tar.gz"
      sha256 "0262ffaab0552395622f02529a8a8329935e5b58823f9a6d3c93802be51f5e24"

      def install
        bin.install "gorepo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gorepo-cli/gorepo/releases/download/v1.2.1/gorepo_1.2.1_linux_amd64.tar.gz"
        sha256 "02c67f06755156d70aa29bd34054e4c22ebcdf9440bd2d90bd781c2de4898d2b"

        def install
          bin.install "gorepo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gorepo-cli/gorepo/releases/download/v1.2.1/gorepo_1.2.1_linux_arm64.tar.gz"
        sha256 "90c42ae6b5ca03b0768819c08b301b88b63d2bef7c2befa56d8b62ab8b97989f"

        def install
          bin.install "gorepo"
        end
      end
    end
  end
end
